### PR TITLE
Replace MeshSequenceController with global functions

### PR DESCRIPTION
**Pull request by neverhood311**

### CODE REVIEW

**Comment by StephenMcAvoy** [comment]
I think with all this traffic you need an Alpha tester. :-P

**Comment by neverhood311** [comment]
@StephenMcAvoy It would seem so. Are you offering? :)

**Comment by StephenMcAvoy** [comment]
I don't want to be pushy but yes.
I just imported three times 140 frames of a Poser sequence of OBJs (Body, dress and hair), successfully. The problem that the last version had with "relative paths" is gone too. :D

**Comment by neverhood311** [comment]
I'll take all the help I can get! I'll be pushing at least a half dozen more alpha releases over the next few months. At some point I'd also like to get some automated testing in place. I've created a [roadmap for version 3](https://github.com/neverhood311/Stop-motion-OBJ/wiki/Version-3-roadmap) if you want to see what's coming down the pipe.

**Comment by StephenMcAvoy** [comment]
GitHub doesn't have a PM facility, does it?
You can drop me an email at mcavoys@aol.com and we can talk.
Stephen

**Pull request merged**
